name: Build ZMK firmware

on:
  workflow_dispatch:
    inputs:
      shield:
        description: 'Shield name (e.g. gyala_proto_v1)'
        required: true
        default: 'gyala_proto_v1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y wget git make gcc g++ unzip libffi-dev cmake ninja-build gperf dfu-util device-tree-compiler python3-pip
          pip3 install west

      - name: Init west
        run: west init -l zmk

      - name: Update west
        run: west update

      - name: Build firmware
        run: |
          west build --pristine -s zmk/app -b seeeduino_xiao_ble -- -DSHIELD=${{ github.event.inputs.shield }}

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: zmk_${{ github.event.inputs.shield }}.uf2
          path: build/zephyr/zmk.uf2
